<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ubunturk" failures="1" tests="9" name="Command line test" time="187.167" errors="0" timestamp="02 Apr 2019 17:49:50 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="47.539"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="30.093"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.98"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.519"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.057"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.5">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;[Failed Scenario]&amp;gt; but was:&amp;lt;[Lütfen email adresinizi giriniz.]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[Failed Scenario]> but was:<[Lütfen email adresinizi giriniz.]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at steps.LoginSteps.checkThe(LoginSteps.java:92)
at ✽.Check the "Failed Scenario"(file:src/test/java/features/Login.feature:21)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="FirstTest" name="myTest" time="10.581"/>
  <testcase classname="SecondTest" name="myTest" time="9.558"/>
  <testcase classname="ThirdTest" name="myTest" time="14.686"/>
</testsuite> <!-- Command line test -->
